/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("CompaniesObjectPageObjectPage journey");

        opaTest("Navigate to CompaniesObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheCompaniesListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheCompaniesListGenerated.onTable().iCheckRows();
            When.onTheCompaniesListGenerated.onTable().iPressRow(0);

            Then.onTheCompaniesObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheCompaniesObjectPageGenerated.iCheckNumberOfSections(2);
            When.onTheCompaniesObjectPageGenerated.iPressSectionIconTabFilterButton("FieldGroup::General");
            Then.onTheCompaniesObjectPageGenerated.iCheckSection({ section: "FieldGroup::General" });
            Then.onTheCompaniesObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "name" });
            Then.onTheCompaniesObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "code" });
            Then.onTheCompaniesObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "country" });
            Then.onTheCompaniesObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "industry/name" });
            Then.onTheCompaniesObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "revenue" });
            Then.onTheCompaniesObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "establishedOn" });
            When.onTheCompaniesObjectPageGenerated.iPressSectionIconTabFilterButton("departments::LineItem");
            Then.onTheCompaniesObjectPageGenerated.iCheckSection({ section: "departments::LineItem" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});