/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("DepartmentsObjectPageObjectPage journey");

        opaTest("Navigate to DepartmentsObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheCompaniesListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheCompaniesListGenerated.onTable().iCheckRows();
            When.onTheCompaniesListGenerated.onTable().iPressRow(0);

            Then.onTheCompaniesObjectPageGenerated.iSeeThisPage();
            Then.onTheCompaniesObjectPageGenerated.onTable({ property: "departments" }).iCheckRows();
            When.onTheCompaniesObjectPageGenerated.onTable({ property: "departments" }).iPressRow(0);

            Then.onTheDepartmentsObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheDepartmentsObjectPageGenerated.iCheckNumberOfSections(2);
            When.onTheDepartmentsObjectPageGenerated.iPressSectionIconTabFilterButton("FieldGroup::General");
            Then.onTheDepartmentsObjectPageGenerated.iCheckSection({ section: "FieldGroup::General" });
            Then.onTheDepartmentsObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "name" });
            Then.onTheDepartmentsObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "code" });
            Then.onTheDepartmentsObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "costCenter" });
            Then.onTheDepartmentsObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "budget" });
            When.onTheDepartmentsObjectPageGenerated.iPressSectionIconTabFilterButton("employees::LineItem");
            Then.onTheDepartmentsObjectPageGenerated.iCheckSection({ section: "employees::LineItem" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});